#!/bin/sh

# ivan mitev - may 2020
# GPL

# show a popup menu (zenity list) with app vms for a given app.
# 
# meant to be used with a window manager's keyboard shortcuts, eg.
# ctrl-alt-x -> popup-appmenu org.gnome.Terminal
# ctrl-alt-f -> popup-appmenu firefox
# ...

# --------------------------------------------

DISPVM_ICON="/usr/share/icons/hicolor/24x24/devices/dispvm-red.png"

MENU_HEIGHT=500
MENU_WIDTH=400
MENU_TIMEOUT=5

DEBUG=

ADD_VM=
ADD_VM="$ADD_VM dispBrowser|$DISPVM_ICON"

# --------------------------------------------

print_d() {
	[ -t 1 -o -n "$DEBUG" ] && echo "$*"
	return 0
}

PROGRAM="$1"

if [ -z "$PROGRAM" ]; then
	echo "Usage: $(basename "$0") name" >&2
	echo "  eg. $(basename "$0") firefox" >&2
	exit 1
fi

# --------------------------------------------
# build a list of VM|icon_file entries

VM_TUPLES=
for vm in $(ls /var/lib/qubes/appvms) ; do

	# don't show apps for sys-* VMs
	[ -z "${vm##sys-*}" ] && continue

	# don't show VMs that don't have $PROGRAM in the vm's shortcuts
	xdg_file="$HOME/.local/share/applications/$vm-${PROGRAM}.desktop"
	[ ! -f "$xdg_file" ] && print_d "no $xdg_file for vm $vm" && continue

	if [ -z "${vm%%*-dvm}" ]; then
		# use a dispVM icon for disp VMs
		qubes_icon=$DISPVM_ICON
	else
		qubes_icon=$(sed -ne 's/^Icon=\(.*\)/\1/p' "$xdg_file")
		[ -z "$qubes_icon" ] && print_d "couldn't find icon in $xdg_file" && continue
	fi

	VM_TUPLES="$VM_TUPLES $vm|$qubes_icon"
done

# Additional VMs
for vm in $ADD_VM; do
	VM_TUPLES="$VM_TUPLES ${vm%|*}|${vm#*|}"
done

# dom0 / xterm
if [ "$PROGRAM" = "xterm" ]; then
	VM_TUPLES="$VM_TUPLES dom0|/usr/share/icons/hicolor/48x48/apps/xterm-color.png"
fi

# --------------------------------------------
# build zenity menu command

MSG="zenity --timeout $MENU_TIMEOUT --height=$MENU_HEIGHT --width=$MENU_WIDTH --list --imagelist"
MSG="$MSG --text="cmd:$PROGRAM" --hide-header --column=\"\" --column=\"\" --print-column 2"

# sort and add entries
for vm_tuple in $(echo $VM_TUPLES | tr ' ' '\n' | sort); do
	vm="${vm_tuple%|*}"
	icon="${vm_tuple#*|}"
	conv_icon="$HOME/icons/$vm/$(basename "$icon")"
	print_d "vm:$vm icon:$icon conv_icon:$conv_icon"

	needconvert=
	[ -f "$conv_icon" ] && [ "$conv_icon" -ot "$qubes_icon" ] && needconvert=1
	[ ! -f "$conv_icon" ] && needconvert=1
	if [ -n "$needconvert" ]; then
		mkdir -p "$(dirname "$conv_icon")"
		convert -resize 24x24 "$icon" "$conv_icon"
	fi

	MSG="$MSG \"$conv_icon\" \"$vm\""
done

print_d "MSG is $MSG"


# --------------------------------------------
# run 

ANS_VM=$(eval $MSG)
RETVAL=$?
[ $RETVAL -ne 0 ] && exit $RETVAL

print_d "ANS_VM:$ANS_VM ANS_PROGRAM:$ANS_PROGRAM"

if [ "$ANS_VM" = "dom0" -a "$PROGRAM" = "xterm" ]; then
	xterm &
else
	qvm-run -q -a --service -- "$ANS_VM" "qubes.StartApp+$PROGRAM"
fi

exit 0
